### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = SmwgQQaZpzxqN_hBejgGuCfCqwZCo95nblx7hvTYwU6teMWZfF1FdT-vwwRHBJ10HxUyix6ghj56l-pKW2RJs8fp8H7PSPeu

### send POST request with json body
POST http://localhost:8080/ignore-csrf
Content-Type: application/json

### GET request with a header
GET http://localhost:8080
Content-Type: application/json

### Send GET request with json body
GET http://localhost:8080/csrfToken
Content-Type: application/json
